### ISSUE TITLE
problème lors de la soumission d'une nouvelle falaise

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-api#1]
Lorsque j'essai d'ajouter une nouvelle falaise (Contribuer -> Nouvelle Falaise) j'ai une erreur 
![erreur_oblik_ajout_falaise](https://user-images.githubusercontent.com/87929045/126893347-2f2f3c4b-a78e-4ee7-ad04-d7571a44beaa.png)

Champs non remplis : 

- Type de roche
- exposition à la pluie
- ensoleillement
- saisons favorables

**Comment by StephaneMichelet** [comment]
Si je supprime les multiples orientations j'ai pu ajouter correctement la falaise, malgré l'absence des même champs que précédemment.

Lors de l'ajout d'une nouvelle falaise, je reteste les deux manière : j'ai toujours le message d'erreur, je n'arrive pas à ajouter...

En supprimant Voie / Grande Voie, en les remettant, en ajoutant / enlevant "Granite", ça finit par passer... étrange !


Nouveau test avec une troisième falaise : en mettant granite, l'ajout passe du 1er coup.

**Comment by lucien-chastan** [comment]
Corrigé ! 
https://github.com/oblyk/oblyk-api/commit/aaa8a4cd20af056f674d82b2e093e2835da93f24

Merci :)
