### ISSUE TITLE
Amélioration : Numérotation des voie

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-api#2]
Lorsqu'on ajoute une voie, on n'a pas la possibilité d'ajouter le numéro de la voie ?
Je ne sais pas si ce ne serait pas une bonne idée d'avoir ce champs, afin de trier les lignes dans l'ordre (comme sur les topos ?)

Seul bémol possible : dans le cas où plusieurs topo référencent un même lieu (je ne sais pas si ça existe ?), suivent t'ils la même numérotation ?

**Comment by lucien-chastan** [comment]
Hello!

Il y a plusieurs problèmes :
- les topos qui peuvent ne pas découper un site selon les même secteurs
- si on une nouvelle ouverture sui se cale entre plusieurs voies il faut revoir toute la numérotation

Mais surtout, et c'est pour ça que je ne l'ai jamais fais _(malgré le fait qu'on me l'ai souvent demandé)_  c'est que si on sait l'ordre des voies sur le site, Oblyk peut se substituer au topo papier et ce n'est pas le but. le but et d'ajouter des informations sur les voies, pouvoir dire celle qu'on fait, les commenter, connaître les voies d'un site pour faire ça recherche, etc.

C'est l'une des limites que je me suis placé à ne pas franchir pour ne pas faire de l'ombre au topo des équipeurs
