### ISSUE TITLE
Problème : miniature d'un topo n'apparaissant pas dans la topothèque

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-api#3]
Dans ma topothèque, la miniature n'apparaît pas, alors que l'image est bien présente dans la page du topo
![Capture d’écran (1)](https://user-images.githubusercontent.com/87929045/126895571-d349a9ab-c90f-4013-87ec-37387ccddb31.png)

**Comment by lucien-chastan** [comment]
Je pense que c'était juste une temps de chargement un peu long : )
