### ISSUE TITLE
Amélioration : modification d'un secteur

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-api#4]
Il manque (ou je n'ai pas trouvé) la possibilité de modifier le nom d'un secteur (ex : typo, ...)

Par exemple au Roc du Gorb : https://oblyk.org/crags/808/roc-du-gorb

Secteur "Le FOUR" qui devrait être "Le four",
Secteur "La paroi jaune" appelée "Le mur jaune" dans le topo correspondant

**Comment by lucien-chastan** [comment]
Il faut se rendre sur le secteur en soit :

par exemple en cliquant sur le nom du secteur quand tu ouvre une voie :
![Capture d’écran de 2021-08-03 11-48-44](https://user-images.githubusercontent.com/22887119/127995690-5a34a1de-ad3b-49ee-beca-6f39257c742c.png)

puis c'est le petit stylo au niveau de l'entête
![image](https://user-images.githubusercontent.com/22887119/127995363-c1129e64-8f32-4092-b43c-d7ed54bcd842.png)

Mais je te l'accorde ce n'est pas clair ...
