### ISSUE TITLE
Problème dans le système d'authentification

### ISSUE THREAD

**Issue by MisterFruits** [oblyk/oblyk-api#6]
Bonjour,

J'ai essayé de me connecté sans succés (pourtant je suis relativement sur de mon mot de passe), j'ai donc essayé de changer de mot de passe, quand je rentre le nouveau mot de passe on me dit "Les mots de passe ne sont pas identiques ou le lien est trop vieux" alors que je viens de recevoir le lien et que j'ai essayé et vérifé plusieurs fois les nouveaux mots de passe que j'ai fourni.

Il semble y avoir un problème avec le système d'authentification.

Est-ce le bon endroit pour faire le reporter ?

**Comment by lucien-chastan** [comment]
Bonjour MisterFruit,

Il y avait effectivement un problème dans la résiliation du mot de passe.

Peux-tu ressayer ?

pour être sur que tu n'ai pas des anciens fichier en cache, peux-tu rafraîchir Oblyk sans cache (ctrl + maj + r sur un ordinateur, scroller vers le haut jusqu'à une animation de loading sur smartphone)

**Comment by MisterFruits** [comment]
Ça fonctionne nikel, merci ! Je ferme l'issue du coup
