### ISSUE TITLE
Ajout d'un endpoint API `ascents` permettant de retrouver une liste de croix pour un compte donné

### ISSUE THREAD

**Issue by audrasjb** [oblyk/oblyk-api#7]
Hello,
Serait-il envisageable de créer un endpoint `ascents` dans l'API pour retrouver la liste des croix d'un compte donné si le grimpeur ou la grimpeuse a ouvert ses croix publiquement ?

Une sorte d'équivalent de l'export CSV en définitive… dans un premier temps la simple exposition des données de la liste, voire des ids des voies serait déjà vraiment cool (les infos des voies pouvant être retrouvées par la suite en utilisant le endpoint `crag_routes`).

Merci d'avance pour toute réponse, et je peux éventuellement mettre la main à la pâte si besoin :)

**Comment by lucien-chastan** [comment]
Hello @audrasjb 

Je ne vais pas te faire l'affront de m'excuser du temps de réponse ...

Pour l'instant l'usage de l'API par des projets extérieurs n'est plus "maintenue", je m'explique ici https://github.com/oblyk/oblyk-app/issues/194#issuecomment-2466185132

Désolé pour ça : /
