### ISSUE TITLE
Marquer un site/secteur comme "non autorisé" / "non praticable" 

### ISSUE THREAD

**Issue by ThomasLamalle** [oblyk/oblyk-api#8]
Serait il possible de marquer un site comme non autorisé car les propriétaires ne sont plus d'accord (par exemple Cougnaguet dans le Lot) ou bien lorsque les voies de sont plus entretenus (ex Roque de Cor, Lot)?

Je verrais aussi un intérêt à avoir ce marquage mais temporaire seulement, ce qui peut être utile lorsque le site est interdit temporairement seulement.

**Comment by lucien-chastan** [comment]
Salut Thomas

Ce système est déjà en partie là, par exemple : https://oblyk.org/crags/24/bois-de-l-enfer

Mais pour l'instant il faut être admin pour pouvoir poster une alerte, donc je les notes à fur est à mesure qu'on me remonter les interdiction.

Mais j'aimerai réussir à récupérer automatiquement les arrêtés et les fermetures pour nidification par exemple.

J'avais commencé à regarder cette outil : https://biodiv-sports.fr/login/?next=/ pour la faune et la flore sensible 

Et les arrêtés, je pense qu'ils sont public, mais pas forcément disponible facilement

**Comment by ThomasLamalle** [comment]
Ah OK super !
Par contre pour les arrêtés s'il n'y a pas d'API je pense que ça va être assez compliqué...

Est ce que ça te ne faciliterai pas la tâche si on avait un bouton signaler et au bout de X signalements tu pourrais regarder dans le détail ?

**Comment by lucien-chastan** [comment]
Pour l'instant il y a un bouton "Signaler un problème" dans chaque pied de page, c'est principalement par ce biais que les propriétaire, les mairies, ou les clubs me signale l'interdiction d'un site.

Dans tout les cas d'interdiction que j'ai eu, je n'ai pas eu besoin d'avoir plusieurs signalement pour me rendre compte que le site est effectivement interdit. (on parle d'une interdiction tous les ~2 mois, ça reste gérable : )
